/*
 * lib/grib2/params.js — turn a GRIB2 parameter's numbers into a name and units.
 *
 * A GRIB2 message says what it holds as three integers: discipline (Section 0),
 * parameter category and parameter number (Section 4). Nothing in the file
 * spells out "Total precipitation" or "kg m-2" -- that lives in WMO Code Table
 * 4.2, which every reader has to bring with it. lib/grib2/param-table.js is
 * that table, generated by scripts/fetch-grib2-tables.js.
 *
 * TWO THINGS THIS FIXES
 *
 * 1. The C table it replaces keyed on (category, number) and ignored discipline,
 *    which WMO keys on as well. That is not theoretical: its category 7 block
 *    held a verbatim copy of the category 1 moisture list, so cat 7 / num 8
 *    returned "Total precipitation" when discipline 0 category 7 is actually
 *    thermodynamic stability indices.
 *
 * 2. Numbers 192-254 (and categories 192-254) are reserved by WMO for the
 *    originating centre, so they are NOT in Table 4.2 and cannot be resolved
 *    without knowing who wrote the file. On a routine GFS file this is the
 *    majority of the problem: of 50 parameters the library could not name, 32
 *    were in this local range and only 18 in the WMO range.
 *
 * Returns null when nothing matches, which is honest: the caller keeps whatever
 * fallback label it already had rather than being handed a guess.
 */
import { WMO, LOCAL, CENTRES } from './param-table.js';

/* WMO reserves 192-254 in both axes for the originating centre. 255 means
 * "missing" and is not a parameter at all. */
const isLocalRange = (n) => n >= 192 && n <= 254;

/**
 * lookupParam(discipline, category, number, centre) -> { name, units } | null
 *
 * `centre` is the originating centre id from Section 1; pass null/undefined
 * when it is not known, and only the WMO table is consulted.
 *
 * The centre's own table is checked FIRST, but only for the local range. A
 * centre may not override a WMO-defined parameter: below 192 the standard is
 * the standard, and letting a local file redefine "Temperature" would make the
 * same numbers mean different things in different files for no good reason.
 */
export function lookupParam(discipline, category, number, centre) {
  if (!Number.isInteger(discipline) || !Number.isInteger(category) ||
      !Number.isInteger(number)) return null;
  if (number === 255 || category === 255) return null;          // "missing"

  const key = `${discipline}.${category}.${number}`;

  if ((isLocalRange(number) || isLocalRange(category)) && centre != null) {
    const table = LOCAL[centre];
    const hit = table && table[key];
    if (hit) return { name: hit[0], units: hit[1] };
  }

  const wmo = WMO[key];
  return wmo ? { name: wmo[0], units: wmo[1] } : null;
}

/**
 * describeCentre(centre) -> string | null — the centre's name, for diagnostics.
 * Only centres whose local parameters ship are known; everything else is a
 * number we have no table for, which is worth being able to say out loud.
 */
export function describeCentre(centre) {
  return (centre != null && CENTRES[centre]) || null;
}

/**
 * paramsFromMessages(messages) -> Map "<cat>.<num>" -> { name, units, discipline, centre }
 *
 * Collapses a walked message list (lib/grib2/grib2-index.js) into the lookup
 * the scan path needs. Variables there are identified by (cat, num) alone, so
 * this resolves the discipline and centre per message and keys the result the
 * way the caller already thinks.
 *
 * Entries are returned for parameters that did NOT resolve too, with name and
 * units null. The discipline is still worth having in that case: it is the
 * difference between a caller reporting "cat=3, num=196" and reporting which
 * discipline those numbers were read under.
 *
 * Where messages disagree -- a file mixing disciplines can legitimately carry
 * the same (cat, num) under two of them, and GFS does: disciplines 0, 2 and 10
 * in one file -- the first RESOLVED answer wins, so a later unresolvable
 * message cannot displace a good name that an earlier one produced.
 */
export function paramsFromMessages(messages) {
  const out = new Map();
  for (const m of messages || []) {
    if (m.cat == null || m.num == null || m.cat < 0 || m.num < 0) continue;
    const key = `${m.cat}.${m.num}`;
    const existing = out.get(key);
    if (existing && existing.name) continue;                  // already resolved
    const hit = lookupParam(m.discipline, m.cat, m.num,
                            m.centre >= 0 ? m.centre : null);
    out.set(key, {
      name: hit ? hit.name : null,
      units: hit ? hit.units : null,
      discipline: m.discipline,
      centre: m.centre >= 0 ? m.centre : null,
    });
  }
  return out;
}
